verify_blog:
  description: >
    Review the generated blog content to ensure it follows the  
    strict guidelines. Utilize your tools
    to read the author's notes. Additionally, if you believe there 
    are any issues with the blog or ways it could be improved, 
    such as the structure of the blog, rhythm, writing stlye, 
    tone, word choice, and content, please provide feedback.

    If any of the criterias are not met, the post is considered invalid.
    Provide actionable changes about what is wrong and what actions
    need to be taken to fix the post.

    Your final response must include:
    - Valid: True/False
    - Feedback: Provide commentary if the post fails any of the criteria.

    The review must check the following guidelines:
    - All headers are H3 type "###".
    - All sub-headers are H4 type "####".
    - All code block examples are properly formatted with the code language specified.
    - All links and sources shared in the author's notes are covered in the blog

    Here is the blog_outline:\n\n {blog_outline}
    Here is the topic for the blog: {topic}
    Here is the author's goal for the blog: {goal}
    Here is the title of the blog: {title}

    Here is the blog to verify:
    {blog}
  expected_output: >
    Pass: True/False
    Feedback: Commentary here if failed.
  agent: blog_verifier
